// Single source of truth for the five PatRick offices.
// Used by /contact for display and by lib/schema.js for LocalBusiness JSON-LD.
//
// `address` is the display string (rendered as HTML on /contact); the
// structured street/city/state/zip fields feed schema.org PostalAddress.

export const offices = [
  {
    id: 1,
    slug: "redmond",
    name: "Redmond Office",
    image: "/Img/Redmond_Office.jpg",
    address: "1199 NE Hemlock Ave,<br/>Redmond, OR 97756",
    street: "1199 NE Hemlock Ave",
    city: "Redmond",
    state: "OR",
    zip: "97756",
    phone: "541-923-0703",
    imageRight: false,
  },
  {
    id: 2,
    slug: "springfield",
    name: "Springfield Office",
    image: "/Img/Springfield_Office.jpg",
    address: "1322 N 30th <br/> Springfield, OR 97478",
    street: "1322 N 30th",
    city: "Springfield",
    state: "OR",
    zip: "97478",
    phone: "541-746-7528",
    imageRight: true,
  },
  {
    id: 3,
    slug: "boise",
    name: "Boise Office",
    image: "/Img/Boise_Office.jpg",
    address: "2049 W. Commerce Ave. <br/> Boise, ID 83705",
    street: "2049 W. Commerce Ave.",
    city: "Boise",
    state: "ID",
    zip: "83705",
    phone: "208-376-2667",
    imageRight: false,
  },
  {
    id: 4,
    slug: "ellensburg",
    name: "Ellensburg Office",
    image: "/Img/Ellensburg_Office.jpg",
    address: "1043 W. University Way <br/> Ellensburg, WA 98926",
    street: "1043 W. University Way",
    city: "Ellensburg",
    state: "WA",
    zip: "98926",
    phone: "509-925-1300",
    imageRight: true,
  },
  {
    id: 5,
    slug: "leicester",
    name: "Leicester Office",
    image: "/Img/Asheville_Office.jpg",
    address: "3187 New Leicester Hwy <br/> Leicester, NC 28748",
    street: "3187 New Leicester Hwy",
    city: "Leicester",
    state: "NC",
    zip: "28748",
    phone: "828-683-2182",
    imageRight: false,
  },
];
